name: UpgradeBlocks
version: 1.1.0
main: me.drakyoid.upgradeblocks.UpgradeBlocks
api-version: 1.8.8
authors: [Drakyoid]
description: Upgrade blocks by right clicking them with the block you want to upgrade to.
